### ISSUE TITLE
Running cerbot in dry-run mode error on installation

### ISSUE THREAD

**Issue by NexRX** [notthebee/ansible-easy-vpn#155]
**Describe the issue**
I'm on a fresh install of a Ubuntu Server 22.04 provided by AlphaVPS. I've done the usual firewall configuring (turnt it off for testing) and updates of the system. 
I've configured the wg and auth subdomains for my domain (and i can access them too) but for some reason I'm getting a Certbot error. 
I'm guessing it's having a hard time validating my domain. But I can't seem to find out why.

**Logs** 
```
Domain name: _[redacted]_.co.uk

Running certbot in dry-run mode to test the validity of the domain...
Traceback (most recent call last):
  File "/usr/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot==1.21.0', 'console_scripts', 'certbot')())
  File "/usr/bin/certbot", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 2, in <module>
    from certbot._internal import main as internal_main
  File "/usr/lib/python3/dist-packages/certbot/_internal/main.py", line 17, in <module>
    import josepy as jose
  File "/usr/lib/python3/dist-packages/josepy/__init__.py", line 43, in <module>
    from josepy.json_util import (
  File "/usr/lib/python3/dist-packages/josepy/json_util.py", line 14, in <module>
    from OpenSSL import crypto
  File "/usr/local/lib/python3.10/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/lib/python3.10/dist-packages/OpenSSL/crypto.py", line 1556, in <module>
    class X509StoreFlags(object):
  File "/usr/local/lib/python3.10/dist-packages/OpenSSL/crypto.py", line 1577, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
```

**Environment:**
- Client OS: Windows
- VPS OS Ubuntu 22.04
- VPS Provider AlphaVPS

**Comment by notthebee** [comment]
The issues has already cropped up multiple times: #113 #67  #82

Would you mind running these commands:
```
pip3 install pip --upgrade
pip3 install pyopenssl --upgrade
```
And then re-running the playbook again?
```
cd $HOME/ansible-easy-vpn
bash bootstrap.sh
```

Let me know if that fixes it

**Comment by NexRX** [comment]
Sorry. I did try searching certbot and no titles immediately seemed familiar

I did upgrading python and pip but neither did the trick.

**Comment by NexRX** [comment]
For some reason, just executing the script after wget doesn't do it. I have to cd into the director manually. Thanks for that one!
