### ISSUE TITLE
Script can't read docker.asc file

### ISSUE THREAD

**Issue by MoonSmiley** [notthebee/ansible-easy-vpn#279]
**Describe the issue**
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: apt_pkg.Error: E:Conflicting values set for option Signed-By regarding source https://download.docker.com/linux/debian/ bookworm: /etc/apt/keyrings/docker.asc != /etc/apt/trusted.gpg.d/docker.asc, E:The list of sources could not be read.
fatal: [localhost]: FAILED! => changed=false
  module_stderr: |-
    Traceback (most recent call last):
      File "<stdin>", line 16, in <module>
      File "<frozen runpy>", line 226, in run_module
      File "<frozen runpy>", line 98, in _run_module_code
      File "<frozen runpy>", line 88, in _run_code
      File "/tmp/ansible_apt_repository_payload_nihe22ao/ansible_apt_repository_payload.zip/ansible/modules/apt_repository.py", line 765, in <module>
      File "/tmp/ansible_apt_repository_payload_nihe22ao/ansible_apt_repository_payload.zip/ansible/modules/apt_repository.py", line 742, in main
      File "/usr/lib/python3/dist-packages/apt/cache.py", line 170, in __init__
        self.open(progress)
      File "/usr/lib/python3/dist-packages/apt/cache.py", line 232, in open
        self._cache = apt_pkg.Cache(progress)
                      ^^^^^^^^^^^^^^^^^^^^^^^
    apt_pkg.Error: E:Conflicting values set for option Signed-By regarding source https://download.docker.com/linux/debian/ bookworm: /etc/apt/keyrings/docker.asc != /etc/apt/trusted.gpg.d/docker.asc, E:The list of sources could not be read.
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

File Permissions: 
-rw-r--r-- 1 root root 3817 Feb  7 16:58 /etc/apt/keyrings/docker.asc

**Environment:**
- Client OS: Windows 11 Pro
- VPS OS : Debian 12
- VPS Provider: Hetzner

**Comment by TheBlindHacker** [comment]
I am getting this during testing on Debian 12 as root....

**Comment by TheBlindHacker** [comment]
Fixed my issue by downgrading to Debian 11 works fine

**Comment by Wolfoverflow** [comment]
I had a similar issue on Ubuntu 22.04, the solution was editing the file at /etc/apt/sources.list.d/docker.list and removing every line except for deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu/ jammy stable

**Comment by stankovicst** [comment]
@Wolfoverflow did not work for me
